sudo: required
language: generic
service: 
    - docker

before_install:
    - docker build -t vinodres/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true vinodres/docker-react npm run test